# Generated by Django 4.2.1 on 2023-05-26 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rfid', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('report_date', models.CharField(blank=True, max_length=100, null=True)),
                ('start_hour', models.CharField(blank=True, max_length=100, null=True)),
                ('finish_hour', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Actives',
            fields=[
                ('rfid', models.CharField(default='0', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_hour', models.CharField(blank=True, max_length=100, null=True)),
                ('finish_hour', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.person')),
            ],
        ),
    ]
